Prohaupt.pdf: bericht.tex
	pdflatex bericht.tex
	bibtex bericht
	pdflatex bericht.tex
	pdflatex bericht.tex
	rm -f bericht.toc bericht.log bericht.bbl bericht.blg bericht.aux literatur.bib.bak bericht.out bericht.run.xml bericht-blx.bib 
